[package]
name = "day-07"
version = "0.1.0"
authors = ["David Wagner <mnem@noiseandheat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
regex = "1.4.2"
